apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    versionControlSystem: {{ .Values.versionControlSystem }}
    versionControlPath: {{ .Values.versionControlPath }}