apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.repositoryName }}-namespace-admin-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.repositoryName }}-admin
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.repositoryName }}-namespace-admin
  apiGroup: rbac.authorization.k8s.io
