apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repositoryName }}-admin-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.repositoryName }}-admin
type: kubernetes.io/service-account-token