apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.repositoryName }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    versionControlSystem: {{ .Values.versionControlSystem }}
    versionControlPath: {{ .Values.versionControlPath }}
